##services:
##  postgres:
##    image: postgres:16
##    container_name: necform-postgres
##    restart: always
##    environment:
##      POSTGRES_DB: necform
##      POSTGRES_USER: necform
##      POSTGRES_PASSWORD: necform
##    ports:
##      - "5432:5432"
##    volumes:
##      - necform_pgdata:/var/lib/postgresql/data
##
##volumes:
##  necform_pgdata:
#
#services:
#
#  postgres:
#    image: postgres:16
#    container_name: necform-postgres
#
#    restart: always
#
#    environment:
#      POSTGRES_DB: necform
#      POSTGRES_USER: necform
#      POSTGRES_PASSWORD: necform
#
#    ports:
#      - "5432:5432"
#
#    volumes:
#      - necform_pgdata:/var/lib/postgresql/data
#
#  keycloak:
#
#    image: quay.io/keycloak/keycloak:26.2
#
#    container_name: necform-keycloak
#
#    restart: always
#
#    command: start-dev
#
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#
#    ports:
#      - "8081:8080"
#
#    depends_on:
#      - postgres
#
#volumes:
#  necform_pgdata:



services:

  postgres:
    image: postgres:16
    container_name: necform-postgres

    restart: always

    environment:
      POSTGRES_DB: necform
      POSTGRES_USER: necform
      POSTGRES_PASSWORD: necform

    ports:
      - "5432:5432"

    volumes:
      - necform_pgdata:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:26.2

    container_name: necform-keycloak

    command: start-dev

    restart: always

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/necform

      KC_DB_USERNAME: necform
      KC_DB_PASSWORD: necform

    ports:
      - "8081:8080"

    depends_on:
      - postgres


volumes:
  necform_pgdata: